INSERT INTO rules (id, slug, name, priority, enabled, status, is_fallback, expression, content, published_at) VALUES
('10000000-0000-4000-8000-000000000001','slow-mobile','Slow-network mobile visitors',30,TRUE,'published',FALSE,'{"combinator":"and","items":[{"field":"device","operator":"equals","value":"mobile"},{"field":"network","operator":"equals","value":"slow"}]}','{"headline":"A lighter experience, delivered instantly","subheadline":"EdgeSync adapts the experience for a slower connection without losing the essentials","cta":"View lightweight mode","theme":"casual"}',NOW()),
('10000000-0000-4000-8000-000000000002','french-language','French-speaking visitors',25,TRUE,'published',FALSE,'{"combinator":"and","items":[{"field":"language","operator":"equals","value":"fr"}]}','{"headline":"Une expérience conçue pour votre contexte","subheadline":"Le bon contenu, adapté à chaque visiteur dès la périphérie","cta":"Voir le tableau de bord","theme":"premium"}',NOW()),
('10000000-0000-4000-8000-000000000003','campaign-visitor','Campaign visitors',20,TRUE,'published',FALSE,'{"combinator":"and","items":[{"field":"referrer","operator":"equals","value":"campaign"}]}','{"headline":"Your campaign journey continues here","subheadline":"A focused experience shaped around the path that brought you here","cta":"Continue exploring","theme":"premium"}',NOW()),
('10000000-0000-4000-8000-000000000004','evening-visitor','Evening visitors',15,TRUE,'published',FALSE,'{"combinator":"or","items":[{"field":"localHour","operator":"gte","value":18},{"field":"localHour","operator":"lte","value":5}]}','{"headline":"Personalization that never clocks out","subheadline":"EdgeSync responds to local context around the clock","cta":"Explore the night shift","theme":"default"}',NOW()),
('10000000-0000-4000-8000-000000000005','mobile-us','US Mobile Users',10,TRUE,'published',FALSE,'{"combinator":"and","items":[{"field":"country","operator":"equals","value":"US"},{"field":"device","operator":"equals","value":"mobile"}]}','{"headline":"Lightning-Fast Edge Performance","subheadline":"Deliver personalized content in under 50ms across the US","cta":"View Dashboard","theme":"default"}',NOW()),
('10000000-0000-4000-8000-000000000006','mobile-international','International Mobile Users',9,TRUE,'published',FALSE,'{"combinator":"and","items":[{"field":"country","operator":"not_equals","value":"US"},{"field":"device","operator":"equals","value":"mobile"}]}','{"headline":"Global Edge Network at Your Fingertips","subheadline":"Real-time personalization from edge locations worldwide","cta":"Explore Analytics","theme":"casual"}',NOW()),
('10000000-0000-4000-8000-000000000007','desktop-premium','Desktop Premium Markets',8,TRUE,'published',FALSE,'{"combinator":"and","items":[{"field":"device","operator":"equals","value":"desktop"},{"field":"country","operator":"in","value":["US","GB","CA","AU","NG"]}]}','{"headline":"Enterprise-Grade Personalization Layer","subheadline":"Intelligent content delivery powered by edge computing","cta":"See Performance Metrics","theme":"premium"}',NOW()),
('10000000-0000-4000-8000-000000000008','desktop-default','Desktop Default',5,TRUE,'published',FALSE,'{"combinator":"and","items":[{"field":"device","operator":"equals","value":"desktop"}]}','{"headline":"Smart Personalization at the Edge","subheadline":"Deliver the right content to the right user instantly","cta":"View Dashboard","theme":"default"}',NOW()),
('10000000-0000-4000-8000-000000000009','default','Default Segment',0,TRUE,'published',TRUE,'{"combinator":"and","items":[]}','{"headline":"Edge-Powered Personalization Layer","subheadline":"Real-time intelligent content delivery with sub-50ms latency","cta":"Get Started","theme":"default"}',NOW())
ON CONFLICT (slug) DO NOTHING;
