'use client';

import { useActionState, useState } from 'react';
import { Braces, Eye, Plus, Trash2 } from 'lucide-react';
import type { ContentVariant, ContextField, RuleCondition, RuleGroup, RuleOperator } from '@/lib/types';
import type { StoredRule } from '@/lib/rules/store';
import { saveRuleAction, type SaveRuleState } from './actions';

const fields: ContextField[] = ['country','device','visitor','language','localHour','referrer','network','pathname'];
const operators: RuleOperator[] = ['equals','not_equals','in','not_in','contains','gte','lte'];
const blankCondition: RuleCondition = { field: 'country', operator: 'equals', value: 'NG' };
type EditorRule = { id: string; slug: string; name: string; priority: number; enabled: boolean; status: 'draft' | 'published'; isFallback: boolean; expression: RuleGroup; content: ContentVariant['content'] };

export default function RuleBuilder({ initial }: { initial: StoredRule | null }) {
  const [saveState, formAction] = useActionState(saveRuleAction, { error: null } satisfies SaveRuleState);
  const [rule, setRule] = useState<EditorRule>(() => initial ? { id: initial.id, slug: initial.slug, name: initial.name, priority: initial.priority, enabled: initial.enabled, status: initial.status, isFallback: initial.isFallback, expression: initial.expression, content: initial.content } : { id: '', slug: '', name: '', priority: 10, enabled: true, status: 'draft', isFallback: false, expression: { combinator: 'and', items: [{ ...blankCondition }] }, content: { headline: 'A more relevant experience', subheadline: 'Content selected for this visitor context', cta: 'Explore EdgeSync', theme: 'default' } });
  const [jsonOpen, setJsonOpen] = useState(false);
  const [json, setJson] = useState('');
  const conditions = rule.expression.items.filter((item): item is RuleCondition => !('items' in item));
  const updateCondition = (index: number, patch: Partial<RuleCondition>) => setRule((current) => ({ ...current, expression: { ...current.expression, items: current.expression.items.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } as RuleCondition : item) } }));
  const payload = JSON.stringify(rule);

  function importJson() { try { const parsed = JSON.parse(json); setRule((current) => ({ ...current, ...parsed, id: current.id })); setJsonOpen(false); } catch { window.alert('That JSON is not valid.'); } }

  const clientError = !rule.name.trim() ? 'Give this rule a name.' : !/^[a-z0-9-]{2,120}$/.test(rule.slug) ? 'Use a lowercase slug with at least two letters, numbers, or hyphens.' : null;

  return <form action={formAction} onSubmit={(event) => { if (clientError) event.preventDefault(); }} className="grid gap-6 xl:grid-cols-[1fr_380px]">
    <input type="hidden" name="payload" value={payload} />
    <div className="space-y-6">
      <Panel title="Rule identity"><div className="grid gap-4 sm:grid-cols-2"><Input label="Name" value={rule.name} onChange={(name) => setRule({ ...rule, name })} placeholder="Nigeria mobile offer" required /><Input label="Slug" value={rule.slug} onChange={(slug) => setRule({ ...rule, slug: slug.toLowerCase().replace(/[^a-z0-9-]/g, '-') })} placeholder="ng-mobile-offer" required /><Input label="Priority" type="number" value={String(rule.priority)} onChange={(priority) => setRule({ ...rule, priority: Number(priority) })} /><label className="flex items-center gap-3 self-end rounded-xl border border-white/10 p-3 text-sm"><input type="checkbox" checked={rule.enabled} onChange={(event) => setRule({ ...rule, enabled: event.target.checked })} />Enabled</label></div>{clientError && <p className="mt-3 text-xs text-amber-300">{clientError}</p>}</Panel>
      <Panel title="Audience conditions" action={<select value={rule.expression.combinator} onChange={(event) => setRule({ ...rule, expression: { ...rule.expression, combinator: event.target.value as 'and'|'or' } })} className="rounded-lg border border-white/10 bg-transparent px-3 py-2 text-xs"><option className="bg-[#0d1c18]" value="and">Match all (AND)</option><option className="bg-[#0d1c18]" value="or">Match any (OR)</option></select>}>
        <div className="space-y-2">{conditions.map((condition, index) => <div key={index} className="grid gap-2 rounded-xl border border-white/8 bg-white/[.025] p-3 sm:grid-cols-[1fr_1fr_1.3fr_auto]"><Select value={condition.field} values={fields} onChange={(field) => updateCondition(index, { field: field as ContextField })} /><Select value={condition.operator} values={operators} onChange={(operator) => updateCondition(index, { operator: operator as RuleOperator })} /><input value={Array.isArray(condition.value) ? condition.value.join(',') : condition.value} onChange={(event) => updateCondition(index, { value: ['in','not_in'].includes(condition.operator) ? event.target.value.split(',').map((v) => v.trim()) : ['gte','lte'].includes(condition.operator) ? Number(event.target.value) : event.target.value })} className="rounded-lg border border-white/10 bg-transparent px-3 py-2 text-sm" placeholder="Value" /><button type="button" onClick={() => setRule({ ...rule, expression: { ...rule.expression, items: rule.expression.items.filter((_, itemIndex) => itemIndex !== index) } })} className="grid h-10 w-10 place-items-center rounded-lg text-white/35 hover:bg-red-400/10 hover:text-red-300"><Trash2 size={16} /></button></div>)}</div>
        <button type="button" onClick={() => setRule({ ...rule, expression: { ...rule.expression, items: [...rule.expression.items, { ...blankCondition }] } })} className="mt-3 flex items-center gap-2 rounded-full border border-white/10 px-4 py-2 text-xs"><Plus size={14} />Add condition</button>
      </Panel>
      <Panel title="Content variant"><div className="space-y-4"><Input label="Headline" value={rule.content.headline} onChange={(headline) => setRule({ ...rule, content: { ...rule.content, headline } })} /><label className="block text-sm"><span className="mb-2 block text-white/50">Subheadline</span><textarea value={rule.content.subheadline} onChange={(event) => setRule({ ...rule, content: { ...rule.content, subheadline: event.target.value } })} rows={3} className="w-full rounded-xl border border-white/10 bg-transparent px-4 py-3" /></label><Input label="CTA label" value={rule.content.cta} onChange={(cta) => setRule({ ...rule, content: { ...rule.content, cta } })} /></div></Panel>
      {jsonOpen && <Panel title="JSON import / export"><textarea value={json || JSON.stringify(rule, null, 2)} onChange={(event) => setJson(event.target.value)} rows={14} className="w-full rounded-xl border border-white/10 bg-black/20 p-4 font-mono text-xs" /><button type="button" onClick={importJson} className="mt-3 rounded-full bg-white/10 px-4 py-2 text-xs">Import JSON</button></Panel>}
    </div>
    <aside className="space-y-4 xl:sticky xl:top-6 xl:self-start">
      <div className="rounded-2xl border border-white/10 bg-[#0d1c18] p-5"><div className="mb-5 flex items-center gap-2 text-sm font-medium"><Eye size={16} className="text-[#76f7b2]" />Live content preview</div><div className="rounded-2xl bg-[#f4f8f4] p-6 text-[#10251e]"><p className="text-2xl font-semibold leading-tight tracking-[-.04em]">{rule.content.headline}</p><p className="mt-3 text-sm opacity-60">{rule.content.subheadline}</p><span className="mt-5 inline-block rounded-full bg-[#76f7b2] px-4 py-2 text-xs font-semibold">{rule.content.cta}</span></div></div>
      {(saveState.error || clientError) && <p role="alert" className="rounded-xl border border-red-300/15 bg-red-400/10 px-4 py-3 text-sm text-red-200">{saveState.error || clientError}</p>}<button name="intent" value="publish" disabled={Boolean(clientError)} className="w-full rounded-full bg-[#76f7b2] px-5 py-3 text-sm font-semibold text-[#07110f] disabled:cursor-not-allowed disabled:opacity-40">Publish rule</button><button name="intent" value="draft" disabled={Boolean(clientError)} className="w-full rounded-full border border-white/10 px-5 py-3 text-sm disabled:cursor-not-allowed disabled:opacity-40">Save draft</button><button type="button" onClick={() => { setJson(JSON.stringify(rule, null, 2)); setJsonOpen((value) => !value); }} className="flex w-full items-center justify-center gap-2 rounded-full border border-white/10 px-5 py-3 text-sm"><Braces size={15} />JSON tools</button>
    </aside>
  </form>;
}

function Panel({ title, action, children }: { title: string; action?: React.ReactNode; children: React.ReactNode }) { return <section className="rounded-2xl border border-white/10 bg-white/[.025] p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><h2 className="font-semibold">{title}</h2>{action}</div>{children}</section>; }
function Input({ label, value, onChange, placeholder, type='text', required=false }: { label: string; value: string; onChange: (value:string)=>void; placeholder?: string; type?: string; required?: boolean }) { return <label className="block text-sm"><span className="mb-2 block text-white/50">{label}</span><input type={type} value={value} required={required} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-white/10 bg-transparent px-4 py-3" /></label>; }
function Select({ value, values, onChange }: { value:string; values:string[]; onChange:(value:string)=>void }) { return <select value={value} onChange={(event)=>onChange(event.target.value)} className="rounded-lg border border-white/10 bg-transparent px-3 py-2 text-sm">{values.map((item)=><option className="bg-[#0d1c18]" value={item} key={item}>{item}</option>)}</select>; }
